/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as TensionCastIdRouteImport } from './routes/tension-cast.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TensionCastIdRoute = TensionCastIdRouteImport.update({
  id: '/tension-cast/$id',
  path: '/tension-cast/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/character/$id': typeof CharacterIdRoute
  '/tension-cast/$id': typeof TensionCastIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/character/$id': typeof CharacterIdRoute
  '/tension-cast/$id': typeof TensionCastIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/character/$id': typeof CharacterIdRoute
  '/tension-cast/$id': typeof TensionCastIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/characters' | '/home' | '/character/$id' | '/tension-cast/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/home' | '/character/$id' | '/tension-cast/$id'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/home'
    | '/character/$id'
    | '/tension-cast/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  HomeRoute: typeof HomeRoute
  CharacterIdRoute: typeof CharacterIdRoute
  TensionCastIdRoute: typeof TensionCastIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tension-cast/$id': {
      id: '/tension-cast/$id'
      path: '/tension-cast/$id'
      fullPath: '/tension-cast/$id'
      preLoaderRoute: typeof TensionCastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  HomeRoute: HomeRoute,
  CharacterIdRoute: CharacterIdRoute,
  TensionCastIdRoute: TensionCastIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
